#ifndef CONFIG_H
#define CONFIG_H

#define WIN32_LEAN_AND_MEAN

#include <stdio.h>
#include <windows.h>

#define NUMBER_OF_ENTITIES (2 + 1) // Zero is for NO_ENTITY, i.e. unused
#define WIDTH_PLAYER 6
#define HEIGHT_PLAYER 3
#define HEGIHT_PLAYER_SPRITE_SHEET 27
#define SIZE_PLAYER_SPRITE_SHEET (WIDTH_PLAYER * 27)
#define NUMBER_OF_PLAYER_CIRCLING_SPRITES 8

#define SIZE_MAP
#define WIDTH_SCREEN 98
#define HEIGHT_SCREEN 24
#define SIZE_FRAME ((WIDTH_SCREEN + 1) * HEIGHT_SCREEN + 1)

#define VELOCITY_PLAYER_X 20
#define VELOCITY_PLAYER_Y 10

#define TIME_FRAME (1.0 / 60.0)

#define WIDTH_SPRITE 16
#define HEIGHT_SPRITE 32
#define SIZE_SPRITE (WIDTH_SPRITE * HEIGHT_SPRITE)

#define WIDTH_ENEMY 10
#define HEIGHT_ENEMY 5
#define SIZE_ENEMY (WIDTH_ENEMY * HEIGHT_ENEMY_SPRITE_SHEET)
#define POSITION_X_ENEMY 60
#define POSITION_Y_ENEMY 10
#define NUMBER_OF_ENEMY_BLINKING_SPRITES 2
#define HEIGHT_ENEMY_SPRITE_SHEET 15

#define DIALOGUE_LONG_PAUSE 20
#define DIALOGUE_MEDIUM_PAUSE 15
#define DIALOGUE_SHORT_PAUSE 10

#endif